-- Schlüsseldienst-App – Phase 2: Archiv
-- Diese Datei einmal vollständig im Supabase SQL Editor ausführen.

-- Archiv-Metadaten
create table if not exists public.archiv (
  id bigint generated by default as identity primary key,
  nr text not null unique,
  typ text not null,
  name text,
  dat date,
  saved timestamptz not null default now(),
  pdf_path text,
  email_gesendet_am timestamptz,
  email_empfaenger text
);

-- Falls eine ältere Archiv-Tabelle bereits existiert, fehlende Spalten ergänzen.
alter table public.archiv add column if not exists pdf_path text;
alter table public.archiv add column if not exists email_gesendet_am timestamptz;
alter table public.archiv add column if not exists email_empfaenger text;

alter table public.archiv enable row level security;

drop policy if exists "archiv lesen" on public.archiv;
create policy "archiv lesen"
on public.archiv for select
using (true);

drop policy if exists "archiv schreiben" on public.archiv;
create policy "archiv schreiben"
on public.archiv for insert
with check (true);

drop policy if exists "archiv aktualisieren" on public.archiv;
create policy "archiv aktualisieren"
on public.archiv for update
using (true)
with check (true);

drop policy if exists "archiv loeschen" on public.archiv;
create policy "archiv loeschen"
on public.archiv for delete
using (true);

-- Privater Storage-Bucket für die tatsächlichen PDF-Dateien.
insert into storage.buckets (id, name, public)
values ('berichte', 'berichte', false)
on conflict (id) do nothing;

drop policy if exists "berichte lesen" on storage.objects;
create policy "berichte lesen"
on storage.objects for select
using (bucket_id = 'berichte');

drop policy if exists "berichte hochladen" on storage.objects;
create policy "berichte hochladen"
on storage.objects for insert
with check (bucket_id = 'berichte');

drop policy if exists "berichte aktualisieren" on storage.objects;
create policy "berichte aktualisieren"
on storage.objects for update
using (bucket_id = 'berichte')
with check (bucket_id = 'berichte');

drop policy if exists "berichte loeschen" on storage.objects;
create policy "berichte loeschen"
on storage.objects for delete
using (bucket_id = 'berichte');
